"""Fills the manuscript with numbers computed by experiments W1-W9.

Reads `results/w*/summary.json` and the disclosure-control report of
the deposited dataset (`data/release_summary.json`), and emits one
LaTeX macro file:

    paper/numbers_en.tex

`diagnostics_cbc.tex` inputs it, so every number quoted in the text comes from
the pipeline rather than from a manual edit. Re-run this after any change to the
data and recompile; nothing needs to be retyped by hand. Equations stay in the
manuscript as LaTeX - only the numbers are generated.

This script deliberately lives outside `src/`: it computes nothing, it
only formats existing results for typesetting.

Usage:
    python paper/fill_numbers.py
    python paper/fill_numbers.py --check   # fail if the file is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RESULTS = REPO / "results"
RELEASE = REPO / "data"
HERE = Path(__file__).resolve().parent

# Grid points of C(thr) quoted in the margin table, macro suffix -> margin value.
CTHR_POINTS = {
    "ZeroTen": 0.10, "ZeroEleven": 0.11, "ZeroTwelve": 0.12, "ZeroThirteen": 0.13,
    "ZeroFourteen": 0.14, "ZeroFifteen": 0.15, "ZeroSixteen": 0.16, "ZeroTwenty": 0.20,
}
RESIDUALS = {"Mcv": "r_mcv", "Mch": "r_mch", "Mchc": "r_mchc", "Wbc": "r_wbc"}


def load(name: str) -> dict:
    path = RESULTS / name / "summary.json"
    if not path.exists():
        sys.exit(f"Missing {path} - run src/run_all.py first.")
    return json.loads(path.read_text())


def load_release() -> dict:
    """Disclosure-control report of the deposited dataset (Data Availability)."""
    path = RELEASE / "release_summary.json"
    if not path.exists():
        sys.exit(f"Missing {path} - run src/make_release.py first.")
    return json.loads(path.read_text())


class Macros:
    """Collects macro definitions, keeping the value and its kind of formatting."""

    def __init__(self) -> None:
        self.items: list[tuple[str, str, object, int]] = []

    def add(self, name: str, kind: str, value, decimals: int = 1) -> None:
        if not name.isalpha():
            raise ValueError(f"LaTeX macro names must be letters only: {name!r}")
        self.items.append((name, kind, value, decimals))

    def integer(self, name: str, value) -> None:
        self.add(name, "int", int(round(float(value))))

    def decimal(self, name: str, value, decimals: int = 1) -> None:
        self.add(name, "dec", float(value), decimals)

    def percent(self, name: str, fraction, decimals: int = 1) -> None:
        """Stores a fraction (0..1) as a percentage number, without the % sign."""
        self.add(name, "dec", float(fraction) * 100.0, decimals)

    def literal(self, name: str, text: str) -> None:
        self.add(name, "raw", text)


def render(macros: Macros) -> str:
    """Renders the macro list as a LaTeX file."""
    lines = [
        "% Generated by paper/fill_numbers.py - DO NOT EDIT BY HAND.",
        "% Source: results/w*/summary.json (experiments W1-W10).",
        "",
    ]
    for name, kind, value, decimals in macros.items:
        if kind == "int":
            body = f"{value:,}"
        elif kind == "dec":
            body = f"{value:.{decimals}f}"
        else:
            body = str(value)
        lines.append(f"\\newcommand{{\\{name}}}{{{body}}}")
    return "\n".join(lines) + "\n"


def collect() -> Macros:
    w1, w2, w3 = load("w1_structure"), load("w2_threshold"), load("w3_redundancy")
    w4, w5, w6 = load("w4_unseen"), load("w5_powerlaw"), load("w6_geometry")
    w7, w9 = load("w7_spaceviz"), load("w9_undefined")

    m = Macros()

    # ---- W1: size and concentration of the space -------------------------- #
    m.integer("ResRecordsRaw", w1["n_records_raw"])
    m.integer("ResRecordsKept", w1["n_records"])
    m.integer("ResDropped", w1["n_dropped_undefined"])
    m.percent("ResKeptPct", w1["n_records"] / w1["n_records_raw"])
    m.percent("ResDroppedPct", w1["n_dropped_undefined"] / w1["n_records_raw"], 2)
    m.integer("ResProfiles", w1["n_profiles"])
    cov = w1["coverage_profiles"]
    for key, suffix in (("50%", "Fifty"), ("80%", "Eighty"), ("90%", "Ninety"),
                        ("95%", "NinetyFive"), ("99%", "NinetyNine")):
        m.integer(f"ResCov{suffix}", cov[key])
    m.percent("ResTopOnePct", w1["top1_share"])
    m.integer("ResSingletons", w1["n_singletons"])
    m.percent("ResSingletonPct", w1["singleton_fraction"])
    m.decimal("ResZipfSlope", w1["zipf_ols"]["zipf_slope"], 2)
    m.decimal("ResZipfRsq", w1["zipf_ols"]["zipf_r2"], 2)

    # ---- W2: margin selection --------------------------------------------- #
    m.decimal("ThrArgmax", w2["argmax_C_full_sample"], 2)
    lo, hi = w2["plateau_thr_range"]
    m.decimal("ThrPlateauLo", lo, 2)
    m.decimal("ThrPlateauHi", hi, 2)
    m.percent("ThrPlateauTolPct", w2["plateau_tol"], 0)
    m.integer("ThrBootReps", w2["bootstrap"]["reps"])
    boot = w2["bootstrap"]["argmax_fraction_by_thr"]
    top3 = sorted(boot.items(), key=lambda kv: -kv[1])[:3]
    for (thr, frac), suffix in zip(top3, ("First", "Second", "Third")):
        m.decimal(f"ThrBoot{suffix}Margin", float(thr), 2)
        m.percent(f"ThrBoot{suffix}Pct", frac)
    by_thr = {round(row["thr"], 2): row["C"] for row in w2["table"]}
    for suffix, thr in CTHR_POINTS.items():
        if thr in by_thr:
            m.integer(f"Cthr{suffix}", by_thr[thr])

    # ---- W5: power-law goodness of fit ------------------------------------ #
    m.decimal("PlAlpha", w5["fit"]["alpha"], 2)
    m.integer("PlXmin", w5["fit"]["xmin"])
    m.integer("PlNTail", w5["fit"]["ntail"])
    m.decimal("PlPvalue", w5["p_value"], 3)

    # ---- W3: algebraic redundancy ----------------------------------------- #
    for suffix, key in RESIDUALS.items():
        r = w3["residuals"][key]
        m.decimal(f"Resid{suffix}Median", r["median_abs"], 3)
        m.decimal(f"Resid{suffix}PNinetyNine", r["p99_abs"], 3)
        m.percent(f"Resid{suffix}WithinPct", r["frac_within_rounding"])
    var = w3["variants"]
    for suffix, key in (("VFourteen", "V14"), ("VTen", "V10"), ("VNine", "V9")):
        m.integer(f"Red{suffix}Profiles", var[key]["n_profiles"])
        m.percent(f"Red{suffix}SingletonPct", var[key]["singleton_fraction"])
    base = var["V14"]["n_profiles"]
    for suffix, key in (("VTen", "V10"), ("VNine", "V9")):
        m.percent(f"RedDrop{suffix}Pct", (base - var[key]["n_profiles"]) / base)

    # ---- W6 / W7: geometry and effective diversity ------------------------ #
    ham = w6["hamming_from_allnorm_V14"]
    m.decimal("GeomHammingMean", ham["mean_deviated_analytes"], 2)
    m.integer("GeomHammingMedian", ham["median_deviated_analytes"])
    m.percent("GeomFracZeroPct", ham["frac_0_deviations"])
    m.percent("GeomFracLeOnePct", ham["frac_le1"])
    m.percent("GeomFracLeTwoPct", ham["frac_le2"])
    shells = w7["V14"]["icicle"]["shell_record_share"]
    for key, suffix in (("0", "Zero"), ("1", "One"), ("2", "Two"),
                        ("3", "Three"), ("4", "FourPlus")):
        m.percent(f"GeomShell{suffix}Pct", shells[key])
    div = w6["diversity"]
    for suffix, key in (("VFourteen", "V14"), ("VTen", "V10")):
        m.decimal(f"DivShannon{suffix}", div[key]["shannon_H_nats"], 2)
        m.decimal(f"DivHillOne{suffix}", div[key]["hill_q1_expH"], 1)
        m.decimal(f"DivHillTwo{suffix}", div[key]["hill_q2_invSimpson"], 1)
        m.decimal(f"DivPielou{suffix}", div[key]["pielou_evenness"], 2)
        m.integer(f"DivRichness{suffix}", div[key]["S_hill_q0"])

    # ---- W4: unobserved profiles ------------------------------------------ #
    for suffix, key in (("VFourteen", "V14"), ("VTen", "V10")):
        v = w4["variants"][key]
        m.integer(f"Unseen{suffix}Sobs", v["S_obs"])
        m.integer(f"Unseen{suffix}FOne", v["good_turing"]["f1"])
        m.integer(f"Unseen{suffix}FTwo", v["good_turing"]["f2"])
        m.percent(f"Unseen{suffix}PNewPct", v["good_turing"]["P_new_profile"], 2)
        m.percent(f"Unseen{suffix}CoveragePct", v["good_turing"]["sample_coverage"])
        m.integer(f"Unseen{suffix}JackOne", v["other_estimators"]["jackknife1"])
        m.integer(f"Unseen{suffix}JackTwo", v["other_estimators"]["jackknife2"])
        m.integer(f"Unseen{suffix}Ace", v["other_estimators"]["ace"])
        m.integer(f"Unseen{suffix}Chao", v["chao1"]["chao1_corrected"])
        ci = v["chao1"].get("chao1_classic_CI95")
        if ci:                                  # absent when there are no doubletons
            m.integer(f"Unseen{suffix}ChaoLo", ci[0])
            m.integer(f"Unseen{suffix}ChaoHi", ci[1])
        m.decimal(f"Unseen{suffix}EndSlope", v["rarefaction_end_slope_per_record"], 3)
        # how much of the estimated space has actually been seen
        m.percent(f"Unseen{suffix}ObservedPct", v["S_obs"] / v["chao1"]["chao1_corrected"], 0)

    # ---- W9: audit of discarded records ------------------------------------ #
    m.integer("AuditRaw", w9["n_raw"])
    m.integer("AuditDropped", w9["n_dropped"])
    m.percent("AuditDroppedPct", w9["dropped_fraction"], 2)
    m.integer("AuditEmpty", w9["n_fully_empty_records"])
    top_param, top_n = max(w9["missing_by_param"].items(), key=lambda kv: kv[1])
    m.literal("AuditTopMissingName", top_param)
    m.integer("AuditTopMissingN", top_n)

    # ---- deposited dataset: what is released and what is withheld ---------- #
    rel = load_release()
    m.integer("RelMinCount", rel["min_count"])
    m.integer("RelProfilesTotal", rel["n_profiles"])
    m.integer("RelProfilesReleased", rel["profiles_released"])
    m.integer("RelProfilesWithheld", rel["profiles_suppressed"])
    m.decimal("RelProfilesWithheldPct", rel["profiles_suppressed_pct"])
    m.integer("RelRecordsWithheld", rel["records_suppressed"])
    m.decimal("RelRecordsWithheldPct", rel["records_suppressed_pct"], 2)
    m.percent("RelRecordsCoveredPct", 1 - rel["records_suppressed_pct"] / 100, 2)

    return m


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="Do not write; exit non-zero if the file is out of date.")
    args = ap.parse_args()

    macros = collect()
    text = render(macros)
    out = HERE / "numbers_en.tex"

    if args.check:
        if (out.read_text() if out.exists() else "") != text:
            print(f"STALE: {out.name} does not match the current results")
            return 1
        print(f"up to date: {out.name}")
        return 0

    out.write_text(text)
    print(f"wrote {out} ({len(macros.items)} macros)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
